### ISSUE TITLE
Validate and support packaged userscripts 

### ISSUE THREAD

**Issue by tinywrkb** [flathub/org.qutebrowser.qutebrowser#132]
I've been ignoring this for a while, as I haven't been using qutebrowser at all, and I've seen very little activity here on issue tracker. There was no much feedback here from users or interest in the userscripts.

Anyway, back to the subject. Let's start to test and validate the packaged userscripts.  
From the point of view of Flatpak packaging and maintenance, there are a few groups of userscripts:

* Userscripts that depend on already packaged or runtime supplied software.  
There's no much to do here except testing that everything works correctly, and nothing is broken due to sandboxing, and in particular the filesystem mount namespace.
* Userscripts that depends on missing Python modules.  
  * If the dependency tree is simple, not requiring too much effort in keeping the packaging updated, and don't break occasionally, then these modules should be added.
  * If it's too time-consuming to have these modules packaged, then it's better to document how to install these modules with the Flatpak SDK's pip in the Flatpak app's XDG dirs prefix (`~/.var/APP_ID`).
* Userscripts that depends on other Flatpak or host apps.
  These should go through `flatpak-spawn`. A `flatpak-spwan` wrapper for each of the needed executables should be packaged, and it should output a proper error message if host access wasn't explicitly enabled by the user.

Suggestions for other userscripts are welcome.

## Userscripts

* [ ] add-nextcloud-bookmarks
* [ ] add-nextcloud-cookbook
* [ ] cast
* [ ] dmenu_qutebrowser
* [ ] format_json
* [ ] getbib
* [ ] kodi
* [ ] open_download
* [ ] openfeeds
* [ ] password_fill
* [ ] qr
* [ ] qute-bitwarden
* [ ] qute-keepass
* [ ] qute-keepassxc
* [ ] qute-lastpass
* [ ] qute-pass
* [ ] qutedmenu
* [ ] readability
* [ ] readability-js
* [ ] ripbang
* [ ] rss
* [ ] taskadd
* [ ] tor_identity
* [ ] view_in_mpv

## TODO
* [ ] Document installation of Python modules for the sandbox
* [ ] Document adding user custom `flatpak-spawn` wrapper, updating PATH in the sandbox
* [ ] Document allowing `flatpak-spawn` host access
